[tool.check-fixmes]
path = "."
max-age = 180

annotations = [
    "fixme",
    "todo",
]
whitelist = [
    ".pylintrc",
    "README.rst",
    "setup.cfg",
    "docs/*.rst",
]

[tool.check-future-tags]
path = "."

annotations = [
    "fixme",
    "todo",
]
whitelist = [
    "docs/*.rst",
]


[tool.isort]
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 88
lines_after_imports = 2
force_single_line = true
force_sort_within_sections = true
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,TESTS,LOCALFOLDER"
known_tests = ["tests"]
skip = [
    "docs/conf.py",
]


[tool.pylint.MASTER]
load-plugins = [
    "pylint_strict_informational",
]

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
enable = [
    "use-symbolic-message-instead",
    "useless-suppression",
]

disable = [
    "attribute-defined-outside-init",
    "cyclic-import",
    "duplicate-code",
    "fixme",
    "file-ignored",
    "import-outside-toplevel",
    "invalid-name",
    "locally-disabled",
    "missing-docstring",
    "no-member",
    "protected-access",
    "too-few-public-methods",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-public-methods",
    "too-many-statements",
    "ungrouped-imports",
    "unused-argument",
    "wrong-import-order",  # we `isort` with a custom config
]
